### ISSUE TITLE
React refresh overwrites array of anonymous atoms on assignment

### ISSUE THREAD

**Issue by nickbabcock** [pmndrs/swc-jotai#26]
```tsx
import {atom} from "jotai";
const abc = [atom("message")];
console.log(abc.length):
// Outputs undefined
```

Instead `abc` is now an atom (`init`, `read`, `write` properties), so I believe something is causing `abc` to be overwritten.

Amusingly, the following works as expected

```tsx
import {atom} from "jotai";
console.log([atom("message")].length):
// Outputs 1
```

If I remove `@swc-jotai/react-refresh` from the list of swc plugins, it works. What could be the problem?

It seems to be a general problem where assigning a variable with an expression that involves atoms will assume that the variable is the atom.

```tsx
const abc = () => [atom('message')]
// abc is once again an atom
```

A workaround is to wrap the construction in a named function.

```tsx
function abc() {
  return [atom('message')];
}
const foo = abc();
console.log(foo.length) // 1 !
```

**Comment by hikariNTU** [comment]
I've added this to my issue reproduction as well, seems like they are similar issue where atom is included in array and some assignment is not linked correctly

![image](https://github.com/pmndrs/swc-jotai/assets/18393696/538dc172-cc97-444e-8c77-fd29f21f4c15)

- #25 

https://github.com/hikariNTU/jotai-swc-test
