### ISSUE TITLE
Anonymous atoms cause an error in the debugLabel plugin

### ISSUE THREAD

**Issue by kaaloo** [pmndrs/swc-jotai#3]
This type of pattern will cause an error because although it will not be possible to deduce a `debugLabel` for the atom, the pattern is not skipped.

```
const Component = ({ value }) => {
  const valueAtom = useMemo(() => atom({ value }), [value])
  // ...
}
```

The workaround is to use a slightly more verbose form where the transform can do it's job.

```
const Component = ({ value }) => {
  const valueAtom = useMemo(() => {
    const myAtom = atom({ value })
    return myAtom;
  }), [value])
  // ...
}
```

**Comment by Thisen** [comment]
Thanks for the report! Will take a look.

**Comment by Thisen** [comment]
@kaaloo Do you have a reproduction?
I tried creating a test case for this, it seems to work correctly.

Output:
```js
var valueAtom = useMemo(
    function () {
      return atom({
        value: value,
      });
    },
    [value]
  );
  valueAtom.debugLabel = "valueAtom";
  ```

**Comment by Thisen** [comment]
I'll close due to inactivity. Feel free to re-open :)

**Comment by kaaloo** [comment]
@Thisen Sorry, I did not see your reply on this case.  The issue comes up when using the debug label plugin.  See:

https://jotai.org/docs/tools/swc#swc-jotai-debug-label

Your test case thus should not set the debug label because the purpose of the debug label plugin is to set it automatically through a code transform.
