### ISSUE TITLE
Is atomFamily supported?

### ISSUE THREAD

**Issue by martinhath** [pmndrs/swc-jotai#33]
The [`atomFamily`](https://github.com/pmndrs/jotai/blob/main/src/vanilla/utils/atomFamily.ts) utility is a useful function, but it seems that `swc-jotai` either doesn't support it altogether, or that it is buggy. Tests doesn't mention it, and I tried to write a quick test:

```rs
    test_inline!(
        Syntax::default(),
        |_| transform(None, None),
        handle_normal_export,
        r#"
import { atom } from "jotai";
export const one = atom(0);
export const two = atomFamily(() => atom(1));"#,
        r#"
globalThis.jotaiAtomCache = globalThis.jotaiAtomCache || {
  cache: new Map(),
  get(name, inst) { 
    if (this.cache.has(name)) {
      return this.cache.get(name)
    }
    this.cache.set(name, inst)
    return inst
  },
}
import { atom } from "jotai";
export const one = globalThis.jotaiAtomCache.get("atoms.ts/one", atom(0));
export const two = globalThis.jotaiAtomCache.get("atoms.ts/two", atomFamily(() => atom(1)));
"#
    );
```

which outputs 

```Diff < left / right > :
 globalThis.jotaiAtomCache = globalThis.jotaiAtomCache || {
     cache: new Map(),
     get (name, inst) {
         if (this.cache.has(name)) {
             return this.cache.get(name);
         }
         this.cache.set(name, inst);
         return inst;
     }
 };
 import { atom } from "jotai";
 export const one = globalThis.jotaiAtomCache.get("atoms.ts/one", atom(0));
<export const two = globalThis.jotaiAtomCache.get("atoms.ts/two", atomFamily(()=>atom(1)));
>const two = globalThis.jotaiAtomCache.get("atoms.ts/two", atom(1));
```

Two things:
1. `export` is removed for some reason
2. the value in `.get` is just `atom(1)` and nothing else
First time looking at the codebase just now, so not sure if this is intentional or what, but it looks like a bug.

**Comment by martinhath** [comment]
Have done some more digging.

`atomFamily` seems like it should be supported, as it's in the `ATOM_IMPORTS` list in `common/src/constants.rs`. Weird that it's getting omitted here (or that the inserted code is just the `atom`), but that looks like a bug now.

Here's what the [Babel plugin](https://github.com/pmndrs/jotai/blob/main/src/babel/plugin-react-refresh.ts) outputs for the same input as the test above:
```js
export const one = globalThis.jotaiAtomCache.get("/Users/martin/src/state-management/src/jotai.tsx/one", atom(0));
one.debugLabel = "one";
export const two = globalThis.jotaiAtomCache.get("/Users/martin/src/state-management/src/jotai.tsx/two", atomFamily(() => atom(1)));
two.debugLabel = "two";
```

**Comment by dai-shi** [comment]
I wonder if the babel plugin version works as expected. `atomFamily(...)` doesn't return an atom.

To make it work, we would probably need `getParams` implemented in the core. https://github.com/pmndrs/jotai/pull/2679

**Comment by martinhath** [comment]
Update on the test case: adding `import { atomFamily } from "jotai/utils";` makes the test pass.

**Comment by martinhath** [comment]
I hadn't understood that I needed to add the names of my custom atom wrappers to the `atomNames` list in the config, as written in the README. Doing this helped.  

However, I also had to change some of my "higher order atom" functions, from

```ts
export const atomFamily2 = <In, Out, At extends Atom<Out>>(fn: (i: In) => At) =>
  atomFamily(fn, deepEqual);
```
which outputs (note the missing `export` and the wrong `.debugLabel`) 
```js
const atomFamily2 = globalThis.jotaiAtomCache.get("/Users/martin/src/albatross/src/utils/jotai.ts/atomFamily2", atomFamily(fn, deepEqual));
atomFamily2.debugLabel = "atomFamily2";
```

to 
```ts
export const atomFamily2 = <In, Out, At extends Atom<Out>>(
  fn: (i: In) => At,
) => {
  const af = atomFamily(fn, deepEqual);
  return af;
};
```
which outputs
```js
export const atomFamily2 = (fn)=>{
    const af = atomFamily(fn, deepEqual);
    af.debugLabel = "af";
    return af;
};
```

**Comment by martinhath** [comment]
I'll close this, since #36 is a better reproduction of the problems I had.
