### ISSUE TITLE
Upgrade swc_core to 0.98

### ISSUE THREAD

**Issue by Zercerium** [pmndrs/swc-jotai#40]
Hi,
thanks a lot for your great work.
I updated Rspack to v1, they are now using swc_core v0.98. (1.70 - 1.7.18)
https://plugins.swc.rs/versions/range/16

Are there plans to upgrade this plugin to a newer swc_core version?
I'm not really into swc stuff, so sadly no clue how much time and effort is necessary.
Thank you for your time!

**Comment by kevinschaich** [comment]
also would be helpful for `next@^15.0.0`
